# Generated by Django 2.1.7 on 2019-12-23 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('StoreId', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('StoreName', models.CharField(max_length=50)),
                ('StoreAddress', models.CharField(max_length=500)),
                ('StoreImage', models.FileField(upload_to='')),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
