# Generated by Django 2.1.7 on 2019-12-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('StoreId', models.IntegerField(primary_key=True, serialize=False)),
                ('StoreName', models.CharField(max_length=50)),
                ('StoreAddress', models.CharField(max_length=500)),
                ('StoreImage', models.FileField(upload_to='')),
            ],
        ),
    ]
