# Generated by Django 2.1.7 on 2019-12-30 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('DesignId', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('DesignName', models.CharField(max_length=50)),
                ('DesignDesc', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DesignInCategory', to='category.CategorysHome')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allDesign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('DesignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allImagesDesign', to='design.Design')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAtap',
            fields=[
                ('MaterialId', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('MaterialName', models.CharField(max_length=50)),
                ('PriceTotal', models.IntegerField()),
                ('DesignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomAtap', to='design.Design')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCatDalam',
            fields=[
                ('MaterialId', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('MaterialName', models.CharField(max_length=50)),
                ('PriceTotal', models.IntegerField()),
                ('DesignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomCatDalam', to='design.Design')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCatLuar',
            fields=[
                ('MaterialId', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('MaterialName', models.CharField(max_length=50)),
                ('PriceTotal', models.IntegerField()),
                ('DesignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomCatLuar', to='design.Design')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDinding',
            fields=[
                ('MaterialId', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('MaterialName', models.CharField(max_length=50)),
                ('PriceTotal', models.IntegerField()),
                ('DesignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomDinding', to='design.Design')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialLantai',
            fields=[
                ('MaterialId', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('MaterialName', models.CharField(max_length=50)),
                ('PriceTotal', models.IntegerField()),
                ('DesignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomLantai', to='design.Design')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPlafon',
            fields=[
                ('MaterialId', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('MaterialName', models.CharField(max_length=50)),
                ('PriceTotal', models.IntegerField()),
                ('DesignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomPlafon', to='design.Design')),
            ],
        ),
        migrations.CreateModel(
            name='RAB',
            fields=[
                ('RABId', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('WorkName', models.CharField(max_length=50)),
                ('PriceTotal', models.IntegerField()),
                ('DesignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allRAB', to='design.Design')),
            ],
        ),
    ]
