# Generated by Django 2.1.7 on 2019-12-31 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20191230_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='DesignDesc',
            new_name='designDesc',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='DesignId',
            new_name='designId',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='DesignName',
            new_name='designName',
        ),
        migrations.RenameField(
            model_name='designimages',
            old_name='DesignId',
            new_name='designId',
        ),
        migrations.RenameField(
            model_name='materialatap',
            old_name='MaterialId',
            new_name='materialId',
        ),
        migrations.RenameField(
            model_name='materialatap',
            old_name='MaterialName',
            new_name='materialName',
        ),
        migrations.RenameField(
            model_name='materialatap',
            old_name='PriceTotal',
            new_name='priceTotal',
        ),
        migrations.RenameField(
            model_name='materialcatdalam',
            old_name='MaterialId',
            new_name='materialId',
        ),
        migrations.RenameField(
            model_name='materialcatdalam',
            old_name='MaterialName',
            new_name='materialName',
        ),
        migrations.RenameField(
            model_name='materialcatdalam',
            old_name='PriceTotal',
            new_name='priceTotal',
        ),
        migrations.RenameField(
            model_name='materialcatluar',
            old_name='MaterialId',
            new_name='materialId',
        ),
        migrations.RenameField(
            model_name='materialcatluar',
            old_name='MaterialName',
            new_name='materialName',
        ),
        migrations.RenameField(
            model_name='materialcatluar',
            old_name='PriceTotal',
            new_name='priceTotal',
        ),
        migrations.RenameField(
            model_name='materialdinding',
            old_name='MaterialId',
            new_name='materialId',
        ),
        migrations.RenameField(
            model_name='materialdinding',
            old_name='MaterialName',
            new_name='materialName',
        ),
        migrations.RenameField(
            model_name='materialdinding',
            old_name='PriceTotal',
            new_name='priceTotal',
        ),
        migrations.RenameField(
            model_name='materiallantai',
            old_name='MaterialId',
            new_name='materialId',
        ),
        migrations.RenameField(
            model_name='materiallantai',
            old_name='MaterialName',
            new_name='materialName',
        ),
        migrations.RenameField(
            model_name='materiallantai',
            old_name='PriceTotal',
            new_name='priceTotal',
        ),
        migrations.RenameField(
            model_name='materialplafon',
            old_name='MaterialId',
            new_name='materialId',
        ),
        migrations.RenameField(
            model_name='materialplafon',
            old_name='MaterialName',
            new_name='materialName',
        ),
        migrations.RenameField(
            model_name='materialplafon',
            old_name='PriceTotal',
            new_name='priceTotal',
        ),
        migrations.RenameField(
            model_name='rab',
            old_name='DesignId',
            new_name='designId',
        ),
        migrations.RenameField(
            model_name='rab',
            old_name='PriceTotal',
            new_name='priceTotal',
        ),
        migrations.RenameField(
            model_name='rab',
            old_name='RABId',
            new_name='rabId',
        ),
        migrations.RenameField(
            model_name='rab',
            old_name='WorkName',
            new_name='workName',
        ),
        migrations.RemoveField(
            model_name='materialatap',
            name='DesignId',
        ),
        migrations.RemoveField(
            model_name='materialcatdalam',
            name='DesignId',
        ),
        migrations.RemoveField(
            model_name='materialcatluar',
            name='DesignId',
        ),
        migrations.RemoveField(
            model_name='materialdinding',
            name='DesignId',
        ),
        migrations.RemoveField(
            model_name='materiallantai',
            name='DesignId',
        ),
        migrations.RemoveField(
            model_name='materialplafon',
            name='DesignId',
        ),
        migrations.AddField(
            model_name='materialatap',
            name='designId',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='customAtap', to='design.Design'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialcatdalam',
            name='designId',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='customCatDalam', to='design.Design'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialcatluar',
            name='designId',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='customCatLuar', to='design.Design'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialdinding',
            name='designId',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='customDinding', to='design.Design'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiallantai',
            name='designId',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='customLantai', to='design.Design'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialplafon',
            name='designId',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='customPlafon', to='design.Design'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='design',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designInCategory', to='category.CategorysHome', to_field='CategoryId'),
        ),
        migrations.AlterField(
            model_name='designimages',
            name='designId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allImagesDesign', to='design.Design', to_field='DesignId'),
        ),
        migrations.AlterField(
            model_name='rab',
            name='designId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allRAB', to='design.Design', to_field='DesignId'),
        ),
    ]
