# Generated by Django 2.1.7 on 2019-12-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_customer', models.CharField(max_length=10)),
                ('nik', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('kategori', models.IntegerField()),
                ('deskripsi', models.CharField(max_length=500)),
                ('harga', models.IntegerField()),
                ('jumlah', models.IntegerField()),
                ('foto', models.FileField(upload_to='')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
            ],
        ),
    ]
