# Generated by Django 2.1.7 on 2019-12-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='ProductOwner',
        ),
    ]
