# Generated by Django 2.1.7 on 2019-12-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191207_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_product',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id_toko',
        ),
    ]
