# Generated by Django 2.1.7 on 2019-12-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
