# Generated by Django 2.1.7 on 2019-12-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allUsers', '0003_auto_20191226_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Vendor'), (3, 'Store'), (66, 'Admin')], null=True),
        ),
    ]
