# Generated by Django 2.1.7 on 2019-12-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allUsers', '0004_auto_20191227_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Vendor'), (3, 'Store')], null=True),
        ),
    ]
