# Generated by Django 2.1.7 on 2019-12-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allUsers', '0005_auto_20191228_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
