# Generated by Django 2.1.7 on 2019-12-28 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allUsers', '0006_auto_20191228_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
        migrations.AddField(
            model_name='imageuser',
            name='AccId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to=settings.AUTH_USER_MODEL),
        ),
    ]
