# Generated by Django 2.1.7 on 2019-12-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('CategoryId', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategorysHome',
            fields=[
                ('CategoryId', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=50)),
            ],
        ),
    ]
