# Generated by Django 2.1.7 on 2019-12-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('CategoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=50)),
            ],
        ),
    ]
