# Generated by Django 2.1.7 on 2019-12-31 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorys',
            old_name='CategoryId',
            new_name='categoryId',
        ),
        migrations.RenameField(
            model_name='categorys',
            old_name='CategoryName',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='categoryshome',
            old_name='CategoryId',
            new_name='categoryId',
        ),
        migrations.RenameField(
            model_name='categoryshome',
            old_name='CategoryName',
            new_name='categoryName',
        ),
    ]
