# Generated by Django 2.1.7 on 2019-12-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20191219_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='CategoryId',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='categoryshome',
            name='CategoryId',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
