# Generated by Django 2.1.7 on 2019-12-29 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20191226_1344'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InCart', to=settings.AUTH_USER_MODEL)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InCart', to='products.Products')),
            ],
        ),
    ]
