# Generated by Django 2.1.7 on 2019-12-30 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartId',
            new_name='CartId',
        ),
        migrations.AlterField(
            model_name='cart',
            name='CustomerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
