# Generated by Django 2.1.7 on 2019-12-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='StoreId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.Stores'),
            preserve_default=False,
        ),
    ]
