# Generated by Django 2.1.7 on 2019-12-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_storeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='StoreId',
            new_name='Stores',
        ),
    ]
