# Generated by Django 2.1.7 on 2019-12-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('products', '0003_auto_20191215_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Stores',
        ),
        migrations.AddField(
            model_name='products',
            name='StoreId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ProductItems', to='store.Stores'),
            preserve_default=False,
        ),
    ]
