# Generated by Django 2.1.7 on 2019-12-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191215_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductInCategory', to='category.Categorys'),
        ),
    ]
